# Generated by Django 3.1.2 on 2020-10-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermercado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.URLField(default=1234),
            preserve_default=False,
        ),
    ]
