# Generated by Django 3.1.2 on 2020-10-20 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0003_usuario'),
        ('supermercado', '0003_carrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreLista', models.CharField(max_length=100)),
                ('productos', models.ManyToManyField(to='supermercado.Producto')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
